* calling sys.exit in Tango device constructor produces big error * use 'poll' to know if child process is finished instead of 'wait', which is causing problems:
Traceback (most recent call last):
  File "LimaCCDs.py", line 58, in <module>
    LimaCameraType = setup_lima_env(sys.argv)
  File "/users/blissadm/applications/LimaCCDs/EnvHelper.py", line 83, in setup_lima_env
    pobj.wait()
  File "/users/blissadm/python/bliss_python/redhate4/lib/python2.6/subprocess.py", line 1157, in wait
    pid, sts = os.waitpid(self.pid, 0)
OSError: [Errno 10] No child processes